version: "3.9"

x-golang-tmlp:
  &golang-tmlp
  image: github.com/ruskotwo/ready-checker:latest
  restart: on-failure
  env_file:
    - ./config/.env

services:

  ready-checker-telegram:
    <<: *golang-tmlp
    command:
      - "telegram"
    ports:
      - "40002:40001"
      - "30043:3002"

  ready-checker-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    env_file:
      - ./config/.env
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
